# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development: &default
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: dai_development
  pool: 5
  
test:
  <<: *default
  database: dai_test
